name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [closed]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet New Contributors for Creating New PR/Issues.
        uses: actions/first-interaction@v1
        if: github.event.action =='opened' && (github.event_name == 'pull_request' || github.event_name == 'issues')
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: " Hello @${{ github.actor }} !👋 Welcome to the Random APIs repository!🚀⚡
          Thank you and congrats🎉 for opening your very first issue in this project.
          Please make sure not to start working on the issue, unless you get assigned to it.😄"
          pr-message: "Hello @${{ github.actor }} !👋 Welcome to the Random APIs repository!💖 
          Thank you and congrats🎉 for opening your first pull request. Please make sure you have followed our [Contributing Guidelines](https://github.com/ashutoshkrris/Random-APIs#how-to-contribute).🙌🙌 
          We will get back to you as soon as we can 😄."

      - name: Congratulate on every PR merge
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{tojson(github.event.number)}}
          body: |
            @${{ github.event.pull_request.user.login }} Hurray, your PR got merged 🥳🎉. Thanks a bunch. Feel free to take another Issue.💖 All the best for your amazing open source journey ahead 🚀. 